"""empty message

Revision ID: fa37caf08444
Revises: 9cc587044f2f
Create Date: 2020-02-02 03:06:54.792374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa37caf08444'
down_revision = '9cc587044f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_entries', sa.Column('name', sa.String(), nullable=True))
    op.add_column('guest_entries', sa.Column('relation', sa.String(), nullable=True))
    op.add_column('guest_entries', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_entries', 'title')
    op.drop_column('guest_entries', 'relation')
    op.drop_column('guest_entries', 'name')
    # ### end Alembic commands ###
